In [12]:
import pandas as pd
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
from joblib import dump, load
from sklearn.model_selection import learning_curve

In [2]:
def LoadTrainingData():
    trainingdata = pd.read_csv("../TrainTestData/TrainingData.csv")
    y_train = trainingdata["outcome"].values
    trainingdata = trainingdata[["age", "sex", "latitude", "longitude",
                                 "Confirmed", "Deaths", "Recovered", "Active", "Incidence_Rate", "Case-Fatality_Ratio"]]
    X_train = trainingdata.values
    return X_train, y_train

In [3]:
def LoadTestData():
    testdata = pd.read_csv("../TrainTestData/TestData.csv")
    y_test = testdata["outcome"].values
    testdata = testdata[["age", "sex", "latitude", "longitude",
                         "Confirmed", "Deaths", "Recovered", "Active", "Incidence_Rate", "Case-Fatality_Ratio"]]
    X_test = testdata.values
    return X_test, y_test

In [10]:
def BuildingAdaboostModel():
    X_train, y_train = LoadTrainingData()
    model = AdaBoostClassifier(n_estimators=10, learning_rate=1)
    model.fit(X_train, y_train)
    dump(model, 'AdaboostedModel.joblib')

In [8]:
def Evaluation():
    AdaboostedModel = load('AdaboostedModel.joblib')
    X_train, y_train = LoadTrainingData()
    X_test, y_test = LoadTestData()

    # Metric 1: Validation Scores
    print("Training Score " +
          str(AdaboostedModel.score(X_train, y_train)))
    print("Validation Score " +
          str(AdaboostedModel.score(X_test, y_test)))

    # Metric 2: Confusion Matrix
    predicted = AdaboostedModel.predict(X_test)
    matrix = metrics.confusion_matrix(y_test, predicted)
    print("The Confusion Matrix for the prediction is")
    print(matrix)

    # Metric 3: Classification Report
    report = metrics.classification_report(y_test, predicted)
    print(report)

In [ ]:
# def Overfitting():
#     k

In [9]:
def main():
    BuildingAdaboostModel()
    Evaluation()

In [11]:
main()

Training Score 0.7805537917897468
Validation Score 0.7808562562805746
The Confusion Matrix for the prediction is
[[    0  1005    12     1]
 [    0 39361    55     0]
 [    0     0 31349    34]
 [    0 18669    69     2]]


/Applications/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


                 precision    recall  f1-score   support

       deceased       0.00      0.00      0.00      1018
   hospitalized       0.67      1.00      0.80     39416
nonhospitalized       1.00      1.00      1.00     31383
      recovered       0.05      0.00      0.00     18740

       accuracy                           0.78     90557
      macro avg       0.43      0.50      0.45     90557
   weighted avg       0.65      0.78      0.69     90557



In [ ]:

#Predict the response for test dataset
# y_pred = model.predict(X_test)

In [ ]:
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))